Update README.md
alistair23/meta-pine64 pull request #8
Opened 2020-10-05 19:37 UTC by bitbrain-za

Thank you for the assistance.

I've also added the steps I took to get everything running.

2020-10-05 21:03 UTC, alistair23 requested changes
Thanks! I have a few comments

2020-10-05 21:03 UTC, alistair23 commented on README.md
> +Steps:
Can you change this to "One option to simplify setup is to use poky, these are some example steps to do this:"? Not everyone (including me) uses poky.

2020-10-05 21:03 UTC, alistair23 commented on README.md
> +First check your SD card fd using `lsblk`.
file path instead of fd?

2020-10-05 21:03 UTC, alistair23 commented on README.md
> +cd tmp/deploy/images/pine-a64-lts/
Can you point out that this is for Linux?

2020-10-05 21:03 UTC, alistair23 commented on README.md
> +```
Can you use ```shell

2020-10-06 04:56 UTC, bitbrain-za commented
Thank you for the comments. Will make the changes now.

2020-10-06 05:20 UTC, alistair23 approved these changes

2020-10-06 05:21 UTC, alistair23 commented
Looks good, do you mind squashing the two commits into 1. You can then force push to the branch

2020-10-06 10:34 UTC, bitbrain-za commented
> Looks good, do you mind squashing the two commits into 1. You can then force push to the branch

I think that's done on your side. There should be a squash option with the merge?

2020-10-06 14:07 UTC, alistair23 commented
I would prefer to just rebase and merge a single commit.

2020-10-06 20:20 UTC, bitbrain-za commented
Rebase and merged commits

2020-10-06 20:20 UTC, closed without merging

2020-10-11 17:59 UTC, alistair23 commented
Thanks. In future you can just force push to the current branch.

I know it may seem strange if you only use the GitHub interface, but by addressing comments in the original commit it makes a projects history much cleaner and maintains bisectability.